<!-- /modules/companies/views/index/index.phtml -->


<?php echo $this->elements->getTabs(); ?>
<ul class="pager">
  <li class="previous pull-left">
    <?php echo $this->tag->linkTo(array('companies/', '&larr; Go Back')); ?>
  </li>
  <li class="pull-right">
    <?php echo $this->tag->linkTo(array('companies/add', 'Create companies')); ?>
  </li>
</ul>

<h1>Companies Index</h1>

<div class="form-result-placeholder">
  <?php if (isset($err_msg)) {
    echo $err_msg;
  } ?>
</div>
<?php
echo $this->tag->form(array('action' => 'companies/multiple', 'class' => 'form-manage-data')) . "\n";
echo $form->render('csrf', array('value' => $this->security->getToken(), 'data-token-name' => $this->security->getTokenKey())) . "\n";

?>
<table class="table table-bordered table-striped">
  <thead>
  <tr>
    <th></th>
    <th>Id</th>
    <th>Name</th>
    <th>Telephone</th>
    <th>Address</th>
    <th>City</th>
    <th colspan="2">Action</th>
  </tr>
  </thead>

  <tbody>
  <tr>
    <td colspan="2"><button>Select All</button></td>
    <td colspan="6">
      <div class="btn-group">
        <?php echo $this->tag->linkTo(array('companies/index', '<i class="icon-fast-backward"></i> First',
          'class' => 'btn btn-default')); ?>
        <?php echo $this->tag->linkTo(array('companies/index?page=' . $page->before, '<i
                            class="icon-step-backward"></i> Previous', 'class' => 'btn btn-default')); ?>
      </div>
        <span class="help-inline">We have found <?php echo $page->total_pages; ?> pages and right now we are on page <?php echo $page->current; ?></span>
      <div class="btn-group pull-right">
        <?php echo $this->tag->linkTo(array('companies/index?page=' . $page->next, '<i
                            class="icon-step-forward"></i> Next', 'class' => 'btn btn-default')); ?>
        <?php echo $this->tag->linkTo(array('companies/index?page=' . $page->last, '<i
                            class="icon-fast-forward"></i> Last', 'class' => 'btn btn-default')); ?>
      </div>
    </td>
  </tr>
  </tbody>


  <tbody>
  <?php
  if (isset($page->items) && !empty($page->items)) {
  	foreach ($page->items as $company) {
	?>
    <tr>
      <td><?php echo $this->tag->checkField(['id[]', 'value' => $company->id]); ?></td>
      <td><?php echo $company->id; ?></td>
      <td><?php echo $company->companyname; ?></td>
      <td><?php echo $company->work_phone; ?></td>
      <td><?php echo $company->address1; ?></td>
      <td><?php echo $company->city; ?></td>
      <td
        width="7%"><?php echo $this->tag->linkTo(array('companies/edit/' . $company->id, '<i class="glyphicon glyphicon-edit"></i> Edit', 'class' => 'btn btn-default')); ?>
      </td>
      <td
        width="7%"><?php echo $this->tag->linkTo(array('companies/delete/' . $company->id, '<i class="glyphicon glyphicon-remove"></i> Delete', 'class' => 'btn btn-default')); ?>
      </td>
    </tr>
  <?php
  }// endforeach;
  ?>
  </tbody>

  <tbody>
  <tr>
    <td colspan="2"><button type="submit" class="delete-btn">Delete Selected</button></td>
    <td colspan="6">
      <div class="btn-group">
        <?php echo $this->tag->linkTo(array('companies/index', '<i class="icon-fast-backward"></i> First',
          'class' => 'btn btn-default')); ?>
        <?php echo $this->tag->linkTo(array('companies/index?page=' . $page->before, '<i
                            class="icon-step-backward"></i> Previous', 'class' => 'btn btn-default')); ?>
      </div>
      <span class="help-inline">We have found <?php echo $page->total_pages; ?> pages and right now we are on page <?php echo $page->current; ?></span>
      <div class="btn-group pull-right">
        <?php echo $this->tag->linkTo(array('companies/index?page=' . $page->next, '<i
                            class="icon-step-forward"></i> Next', 'class' => 'btn btn-default')); ?>
        <?php echo $this->tag->linkTo(array('companies/index?page=' . $page->last, '<i
                            class="icon-fast-forward"></i> Last', 'class' => 'btn btn-default')); ?>
      </div>
    </td>
  </tr>
  </tbody>

  <?php
  } else {
    ?>
    <tr>
      <td colspan="8">No data.</td>
    </tr>
  <?php }// endif; ?>
</table>

<?php echo $this->tag->endForm(); ?>
