<!-- /modules/invoices/views/index/form.phtml -->

<div class="form-result-placeholder">
  <?php if (isset($err_msg)) {
    echo $err_msg;
  } ?>
</div>

<?php
if ($this->dispatcher->getActionName() == "edit") {
  echo "<h1>Edit an Invoice: (CompanyName)</h1>";
  echo $this->tag->form(array('invoices/save', 'role' => 'form'));
} else {
  echo "<h1>Add an Invoize</h1>";
  echo $this->tag->form(array('invoices/create'));
}
?>

<ul class="pager">
  <li class="previous pull-left">
    <?php echo $this->tag->linkTo(array('invoices', '&larr; Go Back')); ?>
  </li>
  <li class="pull-right">
    <?php echo $this->tag->submitButton(array('Save', 'class' => 'btn btn-success')); ?>
  </li>
</ul>
<?php
echo $this->tag->form(array());

?>

<fieldset>

  <?php foreach ($form as $element) { ?>
    <div class="form-group">
      <?php
      if (!$element instanceof Phalcon\Forms\Element\Hidden)
        echo $element->label();
      ?>
      <?php echo $element->render(array('class' => 'form-control')); ?>
    </div>
  <?php } ?>

</fieldset>


<?php echo $this->tag->endForm(); ?> 
